



with query as(

    SELECT distinct
        student_id,
        student_name,
        student_key,
        local_school_year,
        curr_school,
       curr_grade,
       student_gender,
       student_race,
       diploma_type,
       home_room,
       STUDENT_SPECIAL_ED_CLASS,
       student_home_language,
       ELL2,
       p504,
       AVID,
       homeless,
       ihs,
       migrant_ed,
       title,
       curryr_att,
       curr_cum_gpa,
       on_track,
       NUMBER_OF_DISC_INC,
       disc_at_risk,
       total_credits,
       on_track_credits,
       CREDIT_AT_RISK,
       TOTAL_ACADEMIC_RISK,
       TOTAL_OVERALL_RISK,
       ATTENDANCE_AT_RISK,
       OAKS_MATH_ELA_PL_RISK,
       ELA_D_AND_F_CNT,
       MATH_D_AND_F_CNT,
       SCI_D_AND_F_CNT,
       SS_D_AND_F_CNT,
       DF_COURSE_1,
       DF_COURSE_2,
       DF_COURSE_3,
       DF_COURSE_4,
       DF_COURSE_5,
       DF_COURSE_6,
       MULTIPLE_D_AND_F_IND,
       la_earned,
       la_needed,
       ma_earned,
       ma_needed,
       sc_earned,
       sc_needed,
       ss_earned,
       ss_needed,
       af_earned,
       af_needed,
       he_earned,
       he_needed,
       pe_earned,
       pe_needed,
       os_earned,
       os_needed,
        max(case when rn = 1 and local_semester = 1 then course_name end) tri1_course1,
        max(case when rn = 1 and local_semester = 1 then course_subject end) tri1_subject1,
        max(case when rn = 1 and local_semester = 1 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri1_mark1,
        max(case when rn = 1 and local_semester = 1 then staff_name end)  tri1_staff1,
        max(case when rn = 1 and local_semester = 1 then staff_employee_id end)  tri1_staff_id1,
        
        max(case when rn = 2 and local_semester = 1 then course_name end) tri1_course2,
        max(case when rn = 2 and local_semester = 1 then course_subject end) tri1_subject2,       
        max(case when rn = 2 and local_semester = 1 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri1_mark2,
        max(case when rn = 2 and local_semester = 1 then staff_name end)  tri1_staff2,
        max(case when rn = 2 and local_semester = 1 then staff_employee_id end)  tri1_staff_id2,
        
        max(case when rn = 3 and local_semester = 1 then course_name end) tri1_course3,
        max(case when rn = 3 and local_semester = 1 then course_subject end) tri1_subject3,
        max(case when rn = 3 and local_semester = 1 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri1_mark3,
        max(case when rn = 3 and local_semester = 1 then staff_name end)  tri1_staff3,
        max(case when rn = 3 and local_semester = 1 then staff_employee_id end)  tri1_staff_id3,
        
        max(case when rn = 4 and local_semester = 1 then course_name end) tri1_course4,
        max(case when rn = 4 and local_semester = 1 then course_subject end) tri1_subject4,
        max(case when rn = 4 and local_semester = 1 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri1_mark4,
        max(case when rn = 4 and local_semester = 1 then staff_name end)  tri1_staff4,
        max(case when rn = 4 and local_semester = 1 then staff_employee_id end)  tri1_staff_id4,
        
        max(case when rn = 5 and local_semester = 1 then course_name end) tri1_course5,
        max(case when rn = 5 and local_semester = 1 then course_subject end) tri1_subject5,
        max(case when rn = 5 and local_semester = 1 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri1_mark5,
        max(case when rn = 5 and local_semester = 1 then staff_name end)  tri1_staff5,
        max(case when rn = 5 and local_semester = 1 then staff_employee_id end)  tri1_staff_id5,
        
        max(case when rn = 6 and local_semester = 1 then course_name end) tri1_course6,
        max(case when rn = 6 and local_semester = 1 then course_subject end) tri1_subject6,
        max(case when rn = 6 and local_semester = 1 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri1_mark6,
        max(case when rn = 6 and local_semester = 1 then staff_name end)  tri1_staff6,
        max(case when rn = 6 and local_semester = 1 then staff_employee_id end)  tri1_staff_id6,
        
        max(case when rn = 7 and local_semester = 1 then course_name end) tri1_course7,
        max(case when rn = 7 and local_semester = 1 then course_subject end) tri1_subject7,
        max(case when rn = 7 and local_semester = 1 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri1_mark7,
        max(case when rn = 7 and local_semester = 1 then staff_name end)  tri1_staff7,
        max(case when rn = 7 and local_semester = 1 then staff_employee_id end)  tri1_staff_id7,
        
        max(case when rn = 8 and local_semester = 1 then course_name end) tri1_course8,
        max(case when rn = 8 and local_semester = 1 then course_subject end) tri1_subject8,
        max(case when rn = 8 and local_semester = 1 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri1_mark8,
        max(case when rn = 8 and local_semester = 1 then staff_name end)  tri1_staff8,
        max(case when rn = 8 and local_semester = 1 then staff_employee_id end)  tri1_staff_id8,
       
        max(case when rn = 1 and local_semester = 2 then course_name end) tri2_course1,
        max(case when rn = 1 and local_semester = 2 then course_subject end) tri2_subject1,
        max(case when rn = 1 and local_semester = 2 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri2_mark1,
        max(case when rn = 1 and local_semester = 2 then staff_name end)  tri2_staff1,
        max(case when rn = 1 and local_semester = 2 then staff_employee_id end)  tri2_staff_id1,
        
        max(case when rn = 2 and local_semester = 2 then course_name end) tri2_course2,
        max(case when rn = 2 and local_semester = 2 then course_subject end) tri2_subject2,
        max(case when rn = 2 and local_semester = 2 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri2_mark2,
        max(case when rn = 2 and local_semester = 2 then staff_name end)  tri2_staff2,
        max(case when rn = 2 and local_semester = 2 then staff_employee_id end)  tri2_staff_id2,
        
        max(case when rn = 3 and local_semester = 2 then course_name end) tri2_course3,
        max(case when rn = 3 and local_semester = 2 then course_subject end) tri2_subject3,
        max(case when rn = 3 and local_semester = 2 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri2_mark3,
        max(case when rn = 3 and local_semester = 2 then staff_name end)  tri2_staff3,
        max(case when rn = 3 and local_semester = 2 then staff_employee_id end)  tri2_staff_id3,
        
        max(case when rn = 4 and local_semester = 2 then course_name end) tri2_course4,
        max(case when rn = 4 and local_semester = 2 then course_subject end) tri2_subject4,
        max(case when rn = 4 and local_semester = 2 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri2_mark4,
        max(case when rn = 4 and local_semester = 2 then staff_name end)  tri2_staff4,
        max(case when rn = 4 and local_semester = 2 then staff_employee_id end)  tri2_staff_id4,
        
        max(case when rn = 5 and local_semester = 2 then course_name end) tri2_course5,
        max(case when rn = 5 and local_semester = 2 then course_subject end) tri2_subject5,
        max(case when rn = 5 and local_semester = 2 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri2_mark5,
        max(case when rn = 5 and local_semester = 2 then staff_name end)  tri2_staff5,
        max(case when rn = 5 and local_semester = 2 then staff_employee_id end)  tri2_staff_id5,
        
        max(case when rn = 6 and local_semester = 2 then course_name end) tri2_course6,
        max(case when rn = 6 and local_semester = 2 then course_subject end) tri2_subject6,
        max(case when rn = 6 and local_semester = 2 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri2_mark6,
        max(case when rn = 6 and local_semester = 2 then staff_name end)  tri2_staff6,
        max(case when rn = 6 and local_semester = 2 then staff_employee_id end)  tri2_staff_id6,
        
        max(case when rn = 7 and local_semester = 2 then course_name end) tri2_course7,
        max(case when rn = 7 and local_semester = 2 then course_subject end) tri2_subject7,
        max(case when rn = 7 and local_semester = 2 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri2_mark7,
        max(case when rn = 7 and local_semester = 2 then staff_name end)  tri2_staff7,
        max(case when rn = 7 and local_semester = 2 then staff_employee_id end)  tri2_staff_id7,
        
        max(case when rn = 8 and local_semester = 2 then course_name end) tri2_course8,
        max(case when rn = 8 and local_semester = 2 then course_subject end) tri2_subject8,
        max(case when rn = 8 and local_semester = 2 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri2_mark8,
        max(case when rn = 8 and local_semester = 2 then staff_name end)  tri2_staff8,
        max(case when rn = 8 and local_semester = 2 then staff_employee_id end)  tri2_staff_id8,
    
        max(case when rn = 1 and local_semester = 3 then course_name end) tri3_course1,
        max(case when rn = 1 and local_semester = 3 then course_subject end) tri3_subject1,
        max(case when rn = 1 and local_semester = 3 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri3_mark1,
        max(case when rn = 1 and local_semester = 3 then staff_name end)  tri3_staff1,
        max(case when rn = 1 and local_semester = 3 then staff_employee_id end)  tri3_staff_id1,
        
        max(case when rn = 2 and local_semester = 3 then course_name end) tri3_course2,
        max(case when rn = 2 and local_semester = 3 then course_subject end) tri3_subject2,
        max(case when rn = 2 and local_semester = 3 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri3_mark2,
        max(case when rn = 2 and local_semester = 3 then staff_name end)  tri3_staff2,
        max(case when rn = 2 and local_semester = 3 then staff_employee_id end)  tri3_staff_id2,
        
        max(case when rn = 3 and local_semester = 3 then course_name end) tri3_course3,
        max(case when rn = 3 and local_semester = 3 then course_subject end) tri3_subject3,
        max(case when rn = 3 and local_semester = 3 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri3_mark3,
        max(case when rn = 3 and local_semester = 3 then staff_name end)  tri3_staff3,
        max(case when rn = 3 and local_semester = 3 then staff_employee_id end)  tri3_staff_id3,
        
        max(case when rn = 4 and local_semester = 3 then course_name end) tri3_course4,
        max(case when rn = 4 and local_semester = 3 then course_subject end) tri3_subject4,
        max(case when rn = 4 and local_semester = 3 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri3_mark4,
        max(case when rn = 4 and local_semester = 3 then staff_name end)  tri3_staff4,
        max(case when rn = 4 and local_semester = 3 then staff_employee_id end)  tri3_staff_id4,
        
        max(case when rn = 5 and local_semester = 3 then course_name end) tri3_course5,
        max(case when rn = 5 and local_semester = 3 then course_subject end) tri3_subject5,
        max(case when rn = 5 and local_semester = 3 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri3_mark5,
        max(case when rn = 5 and local_semester = 3 then staff_name end)  tri3_staff5,
        max(case when rn = 5 and local_semester = 3 then staff_employee_id end)  tri3_staff_id5,
        
        max(case when rn = 6 and local_semester = 3 then course_name end) tri3_course6,
        max(case when rn = 6 and local_semester = 3 then course_subject end) tri3_subject6,
        max(case when rn = 6 and local_semester = 3 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri3_mark6,
        max(case when rn = 6 and local_semester = 3 then staff_name end)  tri3_staff6,
        max(case when rn = 6 and local_semester = 3 then staff_employee_id end)  tri3_staff_id6,
        
        max(case when rn = 7 and local_semester = 3 then course_name end) tri3_course7,
        max(case when rn = 7 and local_semester = 3 then course_subject end) tri3_subject7,
        max(case when rn = 7 and local_semester = 3 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri3_mark7,
        max(case when rn = 7 and local_semester = 3 then staff_name end)  tri3_staff7,
        max(case when rn = 7 and local_semester = 3 then staff_employee_id end)  tri3_staff_id7,
        
        max(case when rn = 8 and local_semester = 3 then course_name end) tri3_course8,
        max(case when rn = 8 and local_semester = 3 then course_subject end) tri3_subject8,
        max(case when rn = 8 and local_semester = 3 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri3_mark8,
        max(case when rn = 8 and local_semester = 3 then staff_name end)  tri3_staff8,
        max(case when rn = 8 and local_semester = 3 then staff_employee_id end)  tri3_staff_id8,
      
        OSAS_ELA,
        OSAS_MATH
    
    FROM (
                        SELECT distinct 
                        period_date.local_semester,
                        period_date.local_school_year,
                        dtbl_students.student_name,
                        dtbl_students.student_id,
                        dtbl_students.student_key,
                        course_name,
                        course_subject,
                        SCALE_ABBREVIATION,
                        mark_type,
                        staff_name,
                        staff_employee_id,
                        ESD_StudentDataWall.curr_school,
                        ESD_StudentDataWall.curr_grade,
                        dtbl_students.student_gender,
                        dtbl_students.student_race,
                        MTBL_EWS_STUDENT_SUMMARY.diploma_type,
                        MTBL_EWS_STUDENT_SUMMARY.home_room,
                        ESD_StudentDataWall.STUDENT_SPECIAL_ED_CLASS,
                        MTBL_EWS_STUDENT_SUMMARY.student_home_language,
                        ESD_StudentDataWall.ELL2,
                        ESD_StudentDataWall.p504,
                        ESD_StudentDataWall.AVID,
                        ESD_StudentDataWall.homeless,
                        ESD_StudentDataWall.ihs,
                        ESD_StudentDataWall.migrant_ed,
                        ESD_StudentDataWall.title,
                        ESD_StudentDataWall.curryr_att,
                        ESD_StudentDataWall.curr_cum_gpa,
                        MTBL_EWS_STUDENT_SUMMARY.OAKS_MATH_ELA_PL_RISK,
                        MTBL_EWS_STUDENT_SUMMARY.on_track,
                        MTBL_EWS_STUDENT_SUMMARY.NUMBER_OF_DISC_INC,
                        MTBL_EWS_STUDENT_SUMMARY.disc_at_risk,
                        MTBL_EWS_STUDENT_SUMMARY.total_credits,
                        MTBL_EWS_STUDENT_SUMMARY.on_track_credits,
                        MTBL_EWS_STUDENT_SUMMARY.CREDIT_AT_RISK,
                        MTBL_EWS_STUDENT_SUMMARY.TOTAL_ACADEMIC_RISK,
                        MTBL_EWS_STUDENT_SUMMARY.TOTAL_OVERALL_RISK,
                        MTBL_EWS_STUDENT_SUMMARY.ATTENDANCE_PERCENT,
                        MTBL_EWS_STUDENT_SUMMARY.ATTENDANCE_AT_RISK,
                        MTBL_EWS_STUDENT_SUMMARY.ELA_D_AND_F_CNT,
                        MTBL_EWS_STUDENT_SUMMARY.MATH_D_AND_F_CNT,
                        MTBL_EWS_STUDENT_SUMMARY.SCI_D_AND_F_CNT,
                        MTBL_EWS_STUDENT_SUMMARY.SS_D_AND_F_CNT,
                        MTBL_EWS_STUDENT_SUMMARY.DF_COURSE_1,
                        MTBL_EWS_STUDENT_SUMMARY.DF_COURSE_2,
                        MTBL_EWS_STUDENT_SUMMARY.DF_COURSE_3,
                        MTBL_EWS_STUDENT_SUMMARY.DF_COURSE_4,
                        MTBL_EWS_STUDENT_SUMMARY.DF_COURSE_5,
                        MTBL_EWS_STUDENT_SUMMARY.DF_COURSE_6,
                        MTBL_EWS_STUDENT_SUMMARY.MULTIPLE_D_AND_F_IND,
                        la_earned,
                        la_needed,
                        ma_earned,
                        ma_needed,
                        sc_earned,
                        sc_needed,
                        ss_earned,
                        ss_needed,
                        af_earned,
                        af_needed,
                        he_earned,
                        he_needed,
                        pe_earned,
                        pe_needed,
                        os_earned,
                        os_needed,

                        (select max(case when test_group = 'CE' and DTBL_TESTS.TEST_SUBGROUP = 'Total'
                                  and DTBL_SCHOOL_DATES.LOCAL_SCHOOL_YEAR='2018-2019'  then test_primary_result_code else null end) 
                                  from  K12INTEL_DW.FTBL_TEST_SCORES 
                                  inner JOIN K12INTEL_DW.DTBL_TESTS WITH (NOLOCK) ON FTBL_TEST_SCORES.TESTS_KEY = DTBL_TESTS.TESTS_KEY
                                  inner JOIN K12INTEL_DW.DTBL_SCHOOL_DATES WITH (NOLOCK) ON FTBL_TEST_SCORES.SCHOOL_DATES_KEY = DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY
                                  where FTBL_TEST_SCORES.student_key = dtbl_students.student_key)OSAS_ELA,
                       
                        (select max(case when test_group = 'CM' and DTBL_TESTS.TEST_SUBGROUP = 'Total'
                                  and DTBL_SCHOOL_DATES.LOCAL_SCHOOL_YEAR='2018-2019'  then test_primary_result_code else null end) 
                                  from  K12INTEL_DW.FTBL_TEST_SCORES 
                                  inner JOIN K12INTEL_DW.DTBL_TESTS WITH (NOLOCK) ON FTBL_TEST_SCORES.TESTS_KEY = DTBL_TESTS.TESTS_KEY
                                  inner JOIN K12INTEL_DW.DTBL_SCHOOL_DATES WITH (NOLOCK) ON FTBL_TEST_SCORES.SCHOOL_DATES_KEY = DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY
                                  where FTBL_TEST_SCORES.student_key = dtbl_students.student_key)OSAS_MATH,
                         
                        row_number() over(partition by period_date.local_semester, dtbl_students.student_id ORDER BY course_name) rn
                        
                        FROM K12INTEL_DW.FTBL_STUDENT_SCHEDULES
                        INNER JOIN K12INTEL_DW.DTBL_STUDENTS  WITH (NOLOCK) ON FTBL_STUDENT_SCHEDULES.STUDENT_KEY = DTBL_STUDENTS.STUDENT_KEY
                        LEFT JOIN K12INTEL_DW.FTBL_STUDENT_MARKS WITH (NOLOCK) ON FTBL_STUDENT_SCHEDULES.STUDENT_SCHEDULES_KEY = FTBL_STUDENT_MARKS.STUDENT_SCHEDULES_KEY
                        LEFT JOIN K12INTEL_DW.DTBL_SCALES WITH (NOLOCK) ON FTBL_STUDENT_MARKS.SCALE_KEY = DTBL_SCALES.SCALE_KEY
                        inner join K12INTEL_DW.DTBL_staff WITH (NOLOCK) ON FTBL_STUDENT_SCHEDULES.staff_KEY = DTBL_staff.staff_KEY
                        INNER JOIN K12INTEL_DW.DTBL_COURSES WITH (NOLOCK) ON FTBL_STUDENT_SCHEDULES.COURSE_KEY = DTBL_COURSES.COURSE_KEY
                        INNER JOIN K12INTEL_DW.DTBL_SCHOOLS WITH (NOLOCK) ON FTBL_STUDENT_SCHEDULES.SCHOOL_KEY = DTBL_SCHOOLS.SCHOOL_KEY
                        INNER JOIN K12INTEL_DW.DTBL_SCHOOL_DATES period_date WITH (NOLOCK) ON FTBL_STUDENT_SCHEDULES.SCHOOL_DATES_KEY = period_date.SCHOOL_DATES_KEY                      
                        inner join K12INTEL_REPORTING.MTBL_EWS_STUDENT_SUMMARY on MTBL_EWS_STUDENT_SUMMARY.student_key = DTBL_STUDENTS.student_key
                        INNER JOIN dbo.ESD_StudentDataWall WITH (NOLOCK) ON DTBL_STUDENTS.STUDENT_KEY = ESD_StudentDataWall.STUDENT_KEY
                        inner join dbo.ESD_CreditSummary1 WITH (NOLOCK) ON ESD_CreditSummary1.sis_number = DTBL_STUDENTS.student_id
                        
--DTBL_SCHOOL_DATES.LOCAL_SCHOOL_YEAR='2018-2019' 
WHERE
period_date.LOCAL_SCHOOL_YEAR='2021-2022' 
and MTBL_EWS_STUDENT_SUMMARY.school_year='2021-2022' 
and ESD_CreditSummary1.local_school_year='2021-2022' 

--and student_activity_indicator = 'Active'
--AND dtbl_schools.school_key IN (1)
and dtbl_schools.school_key in (37,1043,33,35,36,3680)
AND 1=1
and course_name not in ('4J Testing Day', 'Teacher Aide')

) d
 GROUP BY
       student_id,
       student_name,
       student_key,
       local_school_year,
       curr_school,
       curr_grade,
       student_gender,
       student_race,
       diploma_type,
       home_room,
       STUDENT_SPECIAL_ED_CLASS,
       student_home_language,
       ELL2,
       p504,
       AVID,
       homeless,
       ihs,
       migrant_ed,
       title,
       curryr_att,
       curr_cum_gpa,
       on_track,
       NUMBER_OF_DISC_INC,
       disc_at_risk,
       total_credits,
       on_track_credits,
       CREDIT_AT_RISK,
       TOTAL_ACADEMIC_RISK,
       TOTAL_OVERALL_RISK,
       ATTENDANCE_AT_RISK,
       OAKS_MATH_ELA_PL_RISK,
       ELA_D_AND_F_CNT,
       MATH_D_AND_F_CNT,
       SCI_D_AND_F_CNT,
       SS_D_AND_F_CNT,
       DF_COURSE_1,
       DF_COURSE_2,
       DF_COURSE_3,
       DF_COURSE_4,
       DF_COURSE_5,
       DF_COURSE_6,
       MULTIPLE_D_AND_F_IND,
        la_earned,
       la_needed,
       ma_earned,
       ma_needed,
       sc_earned,
       sc_needed,
       ss_earned,
       ss_needed,
       af_earned,
       af_needed,
       he_earned,
       he_needed,
       pe_earned,
       pe_needed,
       os_earned,
       os_needed,
        OSAS_ELA,
        OSAS_MATH
)
SELECT distinct
	student_name,
	student_id,
	local_school_year,
	curr_school,
	curr_grade,
	student_gender,
	student_race,
	STUDENT_SPECIAL_ED_CLASS,
	student_home_language,
	ELL2,
	p504,
	AVID,
	homeless,
	ihs,
	migrant_ed,
	title,
	curryr_att,
	diploma_type,
	curr_cum_gpa,
	on_track,
	CREDIT_AT_RISK,
	TOTAL_ACADEMIC_RISK,
	ATTENDANCE_AT_RISK,
	 OAKS_MATH_ELA_PL_RISK,
	OSAS_ELA,
	OSAS_MATH,
	disc_at_risk,
	case when NUMBER_OF_DISC_INC is null then 0 else NUMBER_OF_DISC_INC end,
	TOTAL_OVERALL_RISK,
	ELA_D_AND_F_CNT,
	MATH_D_AND_F_CNT,
	SCI_D_AND_F_CNT,
	 SS_D_AND_F_CNT,
	DF_COURSE_1,
	DF_COURSE_2,
	 DF_COURSE_3,
	DF_COURSE_4,
	DF_COURSE_5,
	DF_COURSE_6,
	MULTIPLE_D_AND_F_IND,
	
	tri1_course1,
	tri1_subject1,
	tri1_mark1,
	tri1_staff1,
	tri1_staff_id1,
	tri1_course2,
	tri1_subject2,
	tri1_mark2,
	tri1_staff2,
	tri1_staff_id2,
	tri1_course3,
	tri1_subject3,
	tri1_mark3,
	tri1_staff3,
	tri1_staff_id3,
	tri1_course4,
	tri1_subject4,
	tri1_mark4,
	tri1_staff4,
	tri1_staff_id4,
	tri1_course5,
	tri1_subject5,
	tri1_mark5,
	tri1_staff5,
	tri1_staff_id5,
	tri1_course6,
	tri1_mark6,
	tri1_staff6,
	tri1_staff_id6,
	tri1_course7,
	tri1_subject7,
	tri1_mark7,
	tri1_staff7,
	tri1_staff_id7,
	tri1_course8,
	tri1_subject8,
	tri1_mark8,
	tri1_staff8,
	tri1_staff_id8,
	
	tri2_course1,
	tri2_subject1,
	tri2_mark1,
	tri2_staff1,
	tri2_staff_id1,
	tri2_course2,
	tri2_subject2,
	tri2_mark2,
	tri2_staff2,
	tri2_staff_id2,
	tri2_course3,
	tri2_subject3,
	tri2_mark3,
	tri2_staff3,
	tri2_staff_id3,
	tri2_course4,
	tri2_subject4,
	tri2_mark4,
	tri2_staff4,
	tri2_staff_id4,
	tri2_course5,
	tri2_subject5,
	tri2_mark5,
	tri2_staff5,
	tri2_staff_id5,
	tri2_course6,
	tri2_subject6,
	tri2_mark6,
	tri2_staff6,
	tri2_staff_id6,
	tri2_course7,
	tri2_subject7,
	tri2_mark7,
	tri2_staff7,
	tri2_staff_id7,
	tri2_course8,
	tri2_subject8,
	tri2_mark8,
	tri2_staff8,
	tri2_staff_id8,
	
	tri3_course1,
	tri3_subject1,
	tri3_mark1,
	tri3_staff1,
	tri3_staff_id1,
	tri3_course2,
	tri3_subject2,
	tri3_mark2,
	tri3_staff2,
	tri3_staff_id2,
	tri3_course3,
	tri3_subject3,
	tri3_mark3,
	tri3_staff3,
	tri3_staff_id3,
	tri3_course4,
	tri3_subject4,
	tri3_mark4,
	tri3_staff4,
	tri3_staff_id4,
	tri3_course5,
	tri3_subject5,
	tri3_mark5,
	tri3_staff5,
	tri3_staff_id5,
	tri3_course6,
	tri3_subject6,
	tri3_mark6,
	tri3_staff6,
	tri3_staff_id6,
	tri3_course7,
	tri3_subject7,
	tri3_mark7,
	tri3_staff7,
	tri3_staff_id7,
	tri3_course8,
	tri3_subject8,
	tri3_mark8,
	tri3_staff8,
	tri3_staff_id8,
	la_earned,
	la_needed,
	ma_earned,
	ma_needed,
	sc_earned,
	sc_needed,
	ss_earned,
	ss_needed,
	af_earned,
	af_needed,
	he_earned,
	he_needed,
	pe_earned,
	pe_needed,
	os_earned,
	os_needed,
	on_track_credits,
	student_key
FROM
	 query
ORDER BY
	student_name,
	student_id,
	local_school_year,
	curr_school,
	curr_grade,
	student_gender,
	student_race,
	STUDENT_SPECIAL_ED_CLASS,
	student_home_language,
	ELL2,
	p504,
	AVID,
	homeless,
	ihs,
	migrant_ed,
	title,
	curryr_att,
	diploma_type,
	curr_cum_gpa,
	on_track,
	CREDIT_AT_RISK,
	TOTAL_ACADEMIC_RISK,
	ATTENDANCE_AT_RISK,
	OAKS_MATH_ELA_PL_RISK,
	OSAS_ELA,
	OSAS_MATH,
	disc_at_risk,
	case when NUMBER_OF_DISC_INC is null then 0 else NUMBER_OF_DISC_INC end,
	TOTAL_OVERALL_RISK,
	ELA_D_AND_F_CNT,
	MATH_D_AND_F_CNT,
	SCI_D_AND_F_CNT,
	SS_D_AND_F_CNT,
	DF_COURSE_1,
	DF_COURSE_2,
	DF_COURSE_3,
	DF_COURSE_4,
	DF_COURSE_5,
	DF_COURSE_6,
	MULTIPLE_D_AND_F_IND,
	tri1_course1,
	tri1_subject1,
	tri1_mark1,
	tri1_staff1,
	tri1_staff_id1,
	tri1_course2,
	tri1_subject2,
	tri1_mark2,
	tri1_staff2,
	tri1_staff_id2,
	tri1_course3,
	tri1_subject3,
	tri1_mark3,
	tri1_staff3,
	tri1_staff_id3,
	tri1_course4,
	tri1_subject4,
	tri1_mark4,
	tri1_staff4,
	tri1_staff_id4,
	tri1_course5,
	tri1_subject5,
	tri1_mark5,
	tri1_staff5,
	tri1_staff_id5,
	tri1_course6,
	tri1_mark6,
	tri1_staff6,
	tri1_staff_id6,
	tri1_course7,
	tri1_subject7,
	tri1_mark7,
	tri1_staff7,
	tri1_staff_id7,
	tri1_course8,
	tri1_subject8,
	tri1_mark8,
	tri1_staff8,
	tri1_staff_id8,
	
	tri2_course1,
	tri2_subject1,
	tri2_mark1,
	tri2_staff1,
	tri2_staff_id1,
	tri2_course2,
	tri2_subject2,
	tri2_mark2,
	tri2_staff2,
	tri2_staff_id2,
	tri2_course3,
	tri2_subject3,
	tri2_mark3,
	tri2_staff3,
	tri2_staff_id3,
	tri2_course4,
	tri2_subject4,
	tri2_mark4,
	tri2_staff4,
	tri2_staff_id4,
	tri2_course5,
	tri2_subject5,
	tri2_mark5,
	tri2_staff5,
	tri2_staff_id5,
	tri2_course6,
	tri2_subject6,
	tri2_mark6,
	tri2_staff6,
	tri2_staff_id6,
	tri2_course7,
	tri2_subject7,
	tri2_mark7,
	tri2_staff7,
	tri2_staff_id7,
	tri2_course8,
	tri2_subject8,
	tri2_mark8,
	tri2_staff8,
	tri2_staff_id8,
	
	tri3_course1,
	tri3_subject1,
	tri3_mark1,
	tri3_staff1,
	tri3_staff_id1,
	tri3_course2,
	tri3_subject2,
	tri3_mark2,
	tri3_staff2,
	tri3_staff_id2,
	tri3_course3,
	tri3_subject3,
	tri3_mark3,
	tri3_staff3,
	tri3_staff_id3,
	tri3_course4,
	tri3_subject4,
	tri3_mark4,
	tri3_staff4,
	tri3_staff_id4,
	tri3_course5,
	tri3_subject5,
	tri3_mark5,
	tri3_staff5,
	tri3_staff_id5,
	tri3_course6,
	tri3_subject6,
	tri3_mark6,
	tri3_staff6,
	tri3_staff_id6,
	tri3_course7,
	tri3_subject7,
	tri3_mark7,
	tri3_staff7,
	tri3_staff_id7,
	tri3_course8,
	tri3_subject8,
	tri3_mark8,
	tri3_staff8,
	tri3_staff_id8,
	
	la_earned,
	la_needed,
	ma_earned,
	ma_needed,
	sc_earned,
	sc_needed,
	ss_earned,
	ss_needed,
	af_earned,
	af_needed,
	he_earned,
	he_needed,
	pe_earned,
	pe_needed,
	os_earned,
	os_needed,
	on_track_credits
	go


SELECT
	dtbl_courses.course_name AS "C943",
	dtbl_courses.course_subject AS "C973",
	dtbl_schools.school_name,
	dtbl_school_dates.local_school_year AS "C821",
	dtbl_school_dates.local_semester AS "C949",
	count(distinct ftbl_student_schedules.STUDENT_KEY) AS "C958"
FROM
	K12INTEL_DW.FTBL_STUDENT_SCHEDULES WITH (NOLOCK) 
	LEFT JOIN K12INTEL_DW.FTBL_STUDENT_MARKS WITH (NOLOCK) ON FTBL_STUDENT_SCHEDULES.STUDENT_SCHEDULES_KEY = FTBL_STUDENT_MARKS.STUDENT_SCHEDULES_KEY and scale_key is not null
	left JOIN K12INTEL_DW.DTBL_SCALES WITH (NOLOCK) ON FTBL_STUDENT_MARKS.SCALE_KEY = DTBL_SCALES.SCALE_KEY
	INNER JOIN K12INTEL_DW.DTBL_COURSE_OFFERINGS WITH (NOLOCK) ON FTBL_STUDENT_SCHEDULES.COURSE_OFFERINGS_KEY = DTBL_COURSE_OFFERINGS.COURSE_OFFERINGS_KEY
	INNER JOIN K12INTEL_DW.DTBL_SCHOOLS WITH (NOLOCK) ON FTBL_STUDENT_SCHEDULES.SCHOOL_KEY = DTBL_SCHOOLS.SCHOOL_KEY
	INNER JOIN K12INTEL_DW.DTBL_SCHOOL_DATES WITH (NOLOCK) ON FTBL_STUDENT_SCHEDULES.SCHOOL_DATES_KEY = DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY
	INNER JOIN K12INTEL_DW.DTBL_STAFF WITH (NOLOCK) ON FTBL_STUDENT_SCHEDULES.STAFF_KEY = DTBL_STAFF.STAFF_KEY
	INNER JOIN K12INTEL_DW.DTBL_STUDENTS WITH (NOLOCK) ON FTBL_STUDENT_SCHEDULES.STUDENT_KEY = DTBL_STUDENTS.STUDENT_KEY
	inner join dbo.ESD_UDStu WITH (NOLOCK) ON ESD_UDStu.sis_number = DTBL_STUDENTS.STUDENT_ID
	INNER JOIN K12INTEL_DW.DTBL_COURSES WITH (NOLOCK) ON FTBL_STUDENT_SCHEDULES.COURSE_KEY = DTBL_COURSES.COURSE_KEY
	INNER JOIN K12INTEL_USERDATA.XTBL_DOMAIN_DECODES DOMAIN_GRADE_CODE WITH (NOLOCK) ON DOMAIN_GRADE_CODE.DOMAIN_NAME = 'GRADE_CODE' AND DOMAIN_GRADE_CODE.DOMAIN_CODE = DTBL_STUDENTS.STUDENT_CURRENT_GRADE_CODE
	
WHERE
	(
		dtbl_school_dates.ROLLING_LOCAL_SCHOOL_YR_NUMBER = 0
		--AND dtbl_courses.COURSE_ACADEMIC_LEVEL NOT IN ('@ERR')
		--AND COURSE_TYPE not in ('NA','@ERR')
		AND COURSE_SUBJECT NOT IN('@ERR','--')
		and schedule_status <> 'Dropped'
		and dtbl_school_dates.local_semester = 3
	)
	AND (
		DTBL_STUDENTS.STUDENT_ACTIVITY_INDICATOR = 'ACTIVE'
	)

	AND (
		dtbl_students.student_current_grade_code IN ('P1', 'PK', 'K', '01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', 'TR')
	)
	AND (
		dtbl_schools.school_key IN (1, 133, 2, 2509, 41, 4, 1032, 40, 68, 3659, 37, 5, 202, 49, 7, 1043, 3679, 3680, 3681, 45, 3677, 3685, 10, 69, 12, 3686, 3663, 3657, 15, 16, 64, 50, 1041, 47, 52, 17, 19, 62, 21, 67, 33, 3655, 2600, 1149, 1349, 1599, 1669, 1031, 55, 116, 61, 22, 23, 3656, 35, 36, 1001, 2604, 25, 26, 129, 27, 3661, 3672, 3673, 59, 48, 31, 44, 3662, 42, 3664, 3687, 2612)
	)
	
GROUP BY
	dtbl_courses.course_name,
	dtbl_courses.course_subject,
	dtbl_schools.school_name,
	dtbl_school_dates.local_school_year,
	dtbl_school_dates.local_semester
ORDER BY
	dtbl_courses.course_name,
	dtbl_courses.course_subject,
	dtbl_schools.school_name,
	dtbl_school_dates.local_school_year,
	dtbl_school_dates.local_semester
go



with query as(

    SELECT distinct
        student_id,
        student_name,
        student_key,
        local_school_year,
        curr_school,
       curr_grade,
       student_gender,
       student_race,
       diploma_type,
       home_room,
       STUDENT_SPECIAL_ED_CLASS,
       student_home_language,
       ELL2,
       p504,
       AVID,
       homeless,
       ihs,
       migrant_ed,
       title,
       curryr_att,
       curr_cum_gpa,
       on_track,
       NUMBER_OF_DISC_INC,
       disc_at_risk,
       total_credits,
       on_track_credits,
       CREDIT_AT_RISK,
       TOTAL_ACADEMIC_RISK,
       TOTAL_OVERALL_RISK,
       ATTENDANCE_AT_RISK,
       OAKS_MATH_ELA_PL_RISK,
       ELA_D_AND_F_CNT,
       MATH_D_AND_F_CNT,
       SCI_D_AND_F_CNT,
       SS_D_AND_F_CNT,
       DF_COURSE_1,
       DF_COURSE_2,
       DF_COURSE_3,
       DF_COURSE_4,
       DF_COURSE_5,
       DF_COURSE_6,
       MULTIPLE_D_AND_F_IND,
       la_earned,
       la_needed,
       ma_earned,
       ma_needed,
       sc_earned,
       sc_needed,
       ss_earned,
       ss_needed,
       af_earned,
       af_needed,
       he_earned,
       he_needed,
       pe_earned,
       pe_needed,
       os_earned,
       os_needed,
        max(case when rn = 1 and local_semester = 1 then course_name end) tri1_course1,
        max(case when rn = 1 and local_semester = 1 then course_subject end) tri1_subject1,
        max(case when rn = 1 and local_semester = 1 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri1_mark1,
        max(case when rn = 1 and local_semester = 1 then staff_name end)  tri1_staff1,
        max(case when rn = 1 and local_semester = 1 then staff_employee_id end)  tri1_staff_id1,
        
        max(case when rn = 2 and local_semester = 1 then course_name end) tri1_course2,
        max(case when rn = 2 and local_semester = 1 then course_subject end) tri1_subject2,       
        max(case when rn = 2 and local_semester = 1 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri1_mark2,
        max(case when rn = 2 and local_semester = 1 then staff_name end)  tri1_staff2,
        max(case when rn = 2 and local_semester = 1 then staff_employee_id end)  tri1_staff_id2,
        
        max(case when rn = 3 and local_semester = 1 then course_name end) tri1_course3,
        max(case when rn = 3 and local_semester = 1 then course_subject end) tri1_subject3,
        max(case when rn = 3 and local_semester = 1 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri1_mark3,
        max(case when rn = 3 and local_semester = 1 then staff_name end)  tri1_staff3,
        max(case when rn = 3 and local_semester = 1 then staff_employee_id end)  tri1_staff_id3,
        
        max(case when rn = 4 and local_semester = 1 then course_name end) tri1_course4,
        max(case when rn = 4 and local_semester = 1 then course_subject end) tri1_subject4,
        max(case when rn = 4 and local_semester = 1 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri1_mark4,
        max(case when rn = 4 and local_semester = 1 then staff_name end)  tri1_staff4,
        max(case when rn = 4 and local_semester = 1 then staff_employee_id end)  tri1_staff_id4,
        
        max(case when rn = 5 and local_semester = 1 then course_name end) tri1_course5,
        max(case when rn = 5 and local_semester = 1 then course_subject end) tri1_subject5,
        max(case when rn = 5 and local_semester = 1 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri1_mark5,
        max(case when rn = 5 and local_semester = 1 then staff_name end)  tri1_staff5,
        max(case when rn = 5 and local_semester = 1 then staff_employee_id end)  tri1_staff_id5,
        
        max(case when rn = 6 and local_semester = 1 then course_name end) tri1_course6,
        max(case when rn = 6 and local_semester = 1 then course_subject end) tri1_subject6,
        max(case when rn = 6 and local_semester = 1 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri1_mark6,
        max(case when rn = 6 and local_semester = 1 then staff_name end)  tri1_staff6,
        max(case when rn = 6 and local_semester = 1 then staff_employee_id end)  tri1_staff_id6,
        
        max(case when rn = 7 and local_semester = 1 then course_name end) tri1_course7,
        max(case when rn = 7 and local_semester = 1 then course_subject end) tri1_subject7,
        max(case when rn = 7 and local_semester = 1 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri1_mark7,
        max(case when rn = 7 and local_semester = 1 then staff_name end)  tri1_staff7,
        max(case when rn = 7 and local_semester = 1 then staff_employee_id end)  tri1_staff_id7,
        
        max(case when rn = 8 and local_semester = 1 then course_name end) tri1_course8,
        max(case when rn = 8 and local_semester = 1 then course_subject end) tri1_subject8,
        max(case when rn = 8 and local_semester = 1 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri1_mark8,
        max(case when rn = 8 and local_semester = 1 then staff_name end)  tri1_staff8,
        max(case when rn = 8 and local_semester = 1 then staff_employee_id end)  tri1_staff_id8,
       
        max(case when rn = 1 and local_semester = 2 then course_name end) tri2_course1,
        max(case when rn = 1 and local_semester = 2 then course_subject end) tri2_subject1,
        max(case when rn = 1 and local_semester = 2 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri2_mark1,
        max(case when rn = 1 and local_semester = 2 then staff_name end)  tri2_staff1,
        max(case when rn = 1 and local_semester = 2 then staff_employee_id end)  tri2_staff_id1,
        
        max(case when rn = 2 and local_semester = 2 then course_name end) tri2_course2,
        max(case when rn = 2 and local_semester = 2 then course_subject end) tri2_subject2,
        max(case when rn = 2 and local_semester = 2 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri2_mark2,
        max(case when rn = 2 and local_semester = 2 then staff_name end)  tri2_staff2,
        max(case when rn = 2 and local_semester = 2 then staff_employee_id end)  tri2_staff_id2,
        
        max(case when rn = 3 and local_semester = 2 then course_name end) tri2_course3,
        max(case when rn = 3 and local_semester = 2 then course_subject end) tri2_subject3,
        max(case when rn = 3 and local_semester = 2 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri2_mark3,
        max(case when rn = 3 and local_semester = 2 then staff_name end)  tri2_staff3,
        max(case when rn = 3 and local_semester = 2 then staff_employee_id end)  tri2_staff_id3,
        
        max(case when rn = 4 and local_semester = 2 then course_name end) tri2_course4,
        max(case when rn = 4 and local_semester = 2 then course_subject end) tri2_subject4,
        max(case when rn = 4 and local_semester = 2 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri2_mark4,
        max(case when rn = 4 and local_semester = 2 then staff_name end)  tri2_staff4,
        max(case when rn = 4 and local_semester = 2 then staff_employee_id end)  tri2_staff_id4,
        
        max(case when rn = 5 and local_semester = 2 then course_name end) tri2_course5,
        max(case when rn = 5 and local_semester = 2 then course_subject end) tri2_subject5,
        max(case when rn = 5 and local_semester = 2 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri2_mark5,
        max(case when rn = 5 and local_semester = 2 then staff_name end)  tri2_staff5,
        max(case when rn = 5 and local_semester = 2 then staff_employee_id end)  tri2_staff_id5,
        
        max(case when rn = 6 and local_semester = 2 then course_name end) tri2_course6,
        max(case when rn = 6 and local_semester = 2 then course_subject end) tri2_subject6,
        max(case when rn = 6 and local_semester = 2 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri2_mark6,
        max(case when rn = 6 and local_semester = 2 then staff_name end)  tri2_staff6,
        max(case when rn = 6 and local_semester = 2 then staff_employee_id end)  tri2_staff_id6,
        
        max(case when rn = 7 and local_semester = 2 then course_name end) tri2_course7,
        max(case when rn = 7 and local_semester = 2 then course_subject end) tri2_subject7,
        max(case when rn = 7 and local_semester = 2 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri2_mark7,
        max(case when rn = 7 and local_semester = 2 then staff_name end)  tri2_staff7,
        max(case when rn = 7 and local_semester = 2 then staff_employee_id end)  tri2_staff_id7,
        
        max(case when rn = 8 and local_semester = 2 then course_name end) tri2_course8,
        max(case when rn = 8 and local_semester = 2 then course_subject end) tri2_subject8,
        max(case when rn = 8 and local_semester = 2 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri2_mark8,
        max(case when rn = 8 and local_semester = 2 then staff_name end)  tri2_staff8,
        max(case when rn = 8 and local_semester = 2 then staff_employee_id end)  tri2_staff_id8,
    
        max(case when rn = 1 and local_semester = 3 then course_name end) tri3_course1,
        max(case when rn = 1 and local_semester = 3 then course_subject end) tri3_subject1,
        max(case when rn = 1 and local_semester = 3 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri3_mark1,
        max(case when rn = 1 and local_semester = 3 then staff_name end)  tri3_staff1,
        max(case when rn = 1 and local_semester = 3 then staff_employee_id end)  tri3_staff_id1,
        
        max(case when rn = 2 and local_semester = 3 then course_name end) tri3_course2,
        max(case when rn = 2 and local_semester = 3 then course_subject end) tri3_subject2,
        max(case when rn = 2 and local_semester = 3 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri3_mark2,
        max(case when rn = 2 and local_semester = 3 then staff_name end)  tri3_staff2,
        max(case when rn = 2 and local_semester = 3 then staff_employee_id end)  tri3_staff_id2,
        
        max(case when rn = 3 and local_semester = 3 then course_name end) tri3_course3,
        max(case when rn = 3 and local_semester = 3 then course_subject end) tri3_subject3,
        max(case when rn = 3 and local_semester = 3 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri3_mark3,
        max(case when rn = 3 and local_semester = 3 then staff_name end)  tri3_staff3,
        max(case when rn = 3 and local_semester = 3 then staff_employee_id end)  tri3_staff_id3,
        
        max(case when rn = 4 and local_semester = 3 then course_name end) tri3_course4,
        max(case when rn = 4 and local_semester = 3 then course_subject end) tri3_subject4,
        max(case when rn = 4 and local_semester = 3 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri3_mark4,
        max(case when rn = 4 and local_semester = 3 then staff_name end)  tri3_staff4,
        max(case when rn = 4 and local_semester = 3 then staff_employee_id end)  tri3_staff_id4,
        
        max(case when rn = 5 and local_semester = 3 then course_name end) tri3_course5,
        max(case when rn = 5 and local_semester = 3 then course_subject end) tri3_subject5,
        max(case when rn = 5 and local_semester = 3 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri3_mark5,
        max(case when rn = 5 and local_semester = 3 then staff_name end)  tri3_staff5,
        max(case when rn = 5 and local_semester = 3 then staff_employee_id end)  tri3_staff_id5,
        
        max(case when rn = 6 and local_semester = 3 then course_name end) tri3_course6,
        max(case when rn = 6 and local_semester = 3 then course_subject end) tri3_subject6,
        max(case when rn = 6 and local_semester = 3 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri3_mark6,
        max(case when rn = 6 and local_semester = 3 then staff_name end)  tri3_staff6,
        max(case when rn = 6 and local_semester = 3 then staff_employee_id end)  tri3_staff_id6,
        
        max(case when rn = 7 and local_semester = 3 then course_name end) tri3_course7,
        max(case when rn = 7 and local_semester = 3 then course_subject end) tri3_subject7,
        max(case when rn = 7 and local_semester = 3 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri3_mark7,
        max(case when rn = 7 and local_semester = 3 then staff_name end)  tri3_staff7,
        max(case when rn = 7 and local_semester = 3 then staff_employee_id end)  tri3_staff_id7,
        
        max(case when rn = 8 and local_semester = 3 then course_name end) tri3_course8,
        max(case when rn = 8 and local_semester = 3 then course_subject end) tri3_subject8,
        max(case when rn = 8 and local_semester = 3 and mark_type = 'Final' then SCALE_ABBREVIATION end) tri3_mark8,
        max(case when rn = 8 and local_semester = 3 then staff_name end)  tri3_staff8,
        max(case when rn = 8 and local_semester = 3 then staff_employee_id end)  tri3_staff_id8,
        OSAS_ELA,
        OSAS_MATH
    
    FROM (
                        SELECT distinct 
                        period_date.local_semester,
                        period_date.local_school_year,
                        dtbl_students.student_name,
                        dtbl_students.student_id,
                        dtbl_students.student_key,
                         course_name,
                        course_subject,
                        SCALE_ABBREVIATION,
                        mark_type,
                        staff_name,
                        staff_employee_id,
                        ESD_StudentDataWall.curr_school,
                        ESD_StudentDataWall.curr_grade,
                        dtbl_students.student_gender,
                        dtbl_students.student_race,
                        MTBL_EWS_STUDENT_SUMMARY.diploma_type,
                        MTBL_EWS_STUDENT_SUMMARY.home_room,
                        ESD_StudentDataWall.STUDENT_SPECIAL_ED_CLASS,
                        MTBL_EWS_STUDENT_SUMMARY.student_home_language,
                        ESD_StudentDataWall.ELL2,
                        ESD_StudentDataWall.p504,
                        ESD_StudentDataWall.AVID,
                        ESD_StudentDataWall.homeless,
                        ESD_StudentDataWall.ihs,
                        ESD_StudentDataWall.migrant_ed,
                        ESD_StudentDataWall.title,
                        ESD_StudentDataWall.curryr_att,
                        ESD_StudentDataWall.curr_cum_gpa,
                        MTBL_EWS_STUDENT_SUMMARY.OAKS_MATH_ELA_PL_RISK,
                        MTBL_EWS_STUDENT_SUMMARY.on_track,
                        MTBL_EWS_STUDENT_SUMMARY.NUMBER_OF_DISC_INC,
                        MTBL_EWS_STUDENT_SUMMARY.disc_at_risk,
                        MTBL_EWS_STUDENT_SUMMARY.total_credits,
                        MTBL_EWS_STUDENT_SUMMARY.on_track_credits,
                        MTBL_EWS_STUDENT_SUMMARY.CREDIT_AT_RISK,
                        MTBL_EWS_STUDENT_SUMMARY.TOTAL_ACADEMIC_RISK,
                        MTBL_EWS_STUDENT_SUMMARY.TOTAL_OVERALL_RISK,
                        MTBL_EWS_STUDENT_SUMMARY.ATTENDANCE_PERCENT,
                        MTBL_EWS_STUDENT_SUMMARY.ATTENDANCE_AT_RISK,
                        MTBL_EWS_STUDENT_SUMMARY.ELA_D_AND_F_CNT,
                        MTBL_EWS_STUDENT_SUMMARY.MATH_D_AND_F_CNT,
                        MTBL_EWS_STUDENT_SUMMARY.SCI_D_AND_F_CNT,
                        MTBL_EWS_STUDENT_SUMMARY.SS_D_AND_F_CNT,
                        MTBL_EWS_STUDENT_SUMMARY.DF_COURSE_1,
                        MTBL_EWS_STUDENT_SUMMARY.DF_COURSE_2,
                        MTBL_EWS_STUDENT_SUMMARY.DF_COURSE_3,
                        MTBL_EWS_STUDENT_SUMMARY.DF_COURSE_4,
                        MTBL_EWS_STUDENT_SUMMARY.DF_COURSE_5,
                        MTBL_EWS_STUDENT_SUMMARY.DF_COURSE_6,
                        MTBL_EWS_STUDENT_SUMMARY.MULTIPLE_D_AND_F_IND,
                        la_earned,
                        la_needed,
                        ma_earned,
                        ma_needed,
                        sc_earned,
                        sc_needed,
                        ss_earned,
                        ss_needed,
                        af_earned,
                        af_needed,
                        he_earned,
                        he_needed,
                        pe_earned,
                        pe_needed,
                        os_earned,
                        os_needed,

                        (select max(case when test_group = 'CE' and DTBL_TESTS.TEST_SUBGROUP = 'Total'
                                  and DTBL_SCHOOL_DATES.LOCAL_SCHOOL_YEAR='2018-2019'  then test_primary_result_code else null end) 
                                  from  K12INTEL_DW.FTBL_TEST_SCORES 
                                  inner JOIN K12INTEL_DW.DTBL_TESTS WITH (NOLOCK) ON FTBL_TEST_SCORES.TESTS_KEY = DTBL_TESTS.TESTS_KEY
                                  inner JOIN K12INTEL_DW.DTBL_SCHOOL_DATES WITH (NOLOCK) ON FTBL_TEST_SCORES.SCHOOL_DATES_KEY = DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY
                                  where FTBL_TEST_SCORES.student_key = dtbl_students.student_key)OSAS_ELA,
                       
                        (select max(case when test_group = 'CM' and DTBL_TESTS.TEST_SUBGROUP = 'Total'
                                  and DTBL_SCHOOL_DATES.LOCAL_SCHOOL_YEAR='2018-2019'  then test_primary_result_code else null end) 
                                  from  K12INTEL_DW.FTBL_TEST_SCORES 
                                  inner JOIN K12INTEL_DW.DTBL_TESTS WITH (NOLOCK) ON FTBL_TEST_SCORES.TESTS_KEY = DTBL_TESTS.TESTS_KEY
                                  inner JOIN K12INTEL_DW.DTBL_SCHOOL_DATES WITH (NOLOCK) ON FTBL_TEST_SCORES.SCHOOL_DATES_KEY = DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY
                                  where FTBL_TEST_SCORES.student_key = dtbl_students.student_key)OSAS_MATH,
                         
                        row_number() over(partition by period_date.local_semester, dtbl_students.student_id ORDER BY course_name) rn
                        
                        FROM K12INTEL_DW.FTBL_STUDENT_SCHEDULES
                        INNER JOIN K12INTEL_DW.DTBL_STUDENTS  WITH (NOLOCK) ON FTBL_STUDENT_SCHEDULES.STUDENT_KEY = DTBL_STUDENTS.STUDENT_KEY
                        inner JOIN K12INTEL_DW.FTBL_STUDENT_MARKS WITH (NOLOCK) ON FTBL_STUDENT_SCHEDULES.STUDENT_SCHEDULES_KEY = FTBL_STUDENT_MARKS.STUDENT_SCHEDULES_KEY 
                        inner JOIN K12INTEL_DW.DTBL_SCALES WITH (NOLOCK) ON FTBL_STUDENT_MARKS.SCALE_KEY = DTBL_SCALES.SCALE_KEY and mark_type = 'Final'
                        inner join K12INTEL_DW.DTBL_staff WITH (NOLOCK) ON FTBL_STUDENT_SCHEDULES.staff_KEY = DTBL_staff.staff_KEY
                        INNER JOIN K12INTEL_DW.DTBL_COURSES WITH (NOLOCK) ON FTBL_STUDENT_SCHEDULES.COURSE_KEY = DTBL_COURSES.COURSE_KEY
                        INNER JOIN K12INTEL_DW.DTBL_SCHOOLS WITH (NOLOCK) ON FTBL_STUDENT_SCHEDULES.SCHOOL_KEY = DTBL_SCHOOLS.SCHOOL_KEY
                        INNER JOIN K12INTEL_DW.DTBL_SCHOOL_DATES period_date WITH (NOLOCK) ON FTBL_STUDENT_SCHEDULES.SCHOOL_DATES_KEY = period_date.SCHOOL_DATES_KEY                      
                        inner join K12INTEL_REPORTING.MTBL_EWS_STUDENT_SUMMARY on MTBL_EWS_STUDENT_SUMMARY.student_key = DTBL_STUDENTS.student_key
                        INNER JOIN dbo.ESD_StudentDataWall WITH (NOLOCK) ON DTBL_STUDENTS.STUDENT_KEY = ESD_StudentDataWall.STUDENT_KEY
                        inner join dbo.ESD_CreditSummary1 WITH (NOLOCK) ON ESD_CreditSummary1.sis_number = DTBL_STUDENTS.student_id
                        
--DTBL_SCHOOL_DATES.LOCAL_SCHOOL_YEAR='2018-2019' 
WHERE
period_date.LOCAL_SCHOOL_YEAR='2018-2019' 
and MTBL_EWS_STUDENT_SUMMARY.school_year='2018-2019' 
and ESD_CreditSummary1.local_school_year='2018-2019' 

--and student_activity_indicator = 'Active'
--AND dtbl_schools.school_key IN (1)
and dtbl_schools.school_key in (37,1043,33,35,36,3680)
AND 1=1
and course_name not in ('4J Testing Day', 'Teacher Aide')

) d
 GROUP BY
       student_id,
       student_name,
       student_key,
       local_school_year,
       curr_school,
       curr_grade,
       student_gender,
       student_race,
       diploma_type,
       home_room,
       STUDENT_SPECIAL_ED_CLASS,
       student_home_language,
       ELL2,
       p504,
       AVID,
       homeless,
       ihs,
       migrant_ed,
       title,
       curryr_att,
       curr_cum_gpa,
       on_track,
       NUMBER_OF_DISC_INC,
       disc_at_risk,
       total_credits,
       on_track_credits,
       CREDIT_AT_RISK,
       TOTAL_ACADEMIC_RISK,
       TOTAL_OVERALL_RISK,
       ATTENDANCE_AT_RISK,
       OAKS_MATH_ELA_PL_RISK,
       ELA_D_AND_F_CNT,
       MATH_D_AND_F_CNT,
       SCI_D_AND_F_CNT,
       SS_D_AND_F_CNT,
       DF_COURSE_1,
       DF_COURSE_2,
       DF_COURSE_3,
       DF_COURSE_4,
       DF_COURSE_5,
       DF_COURSE_6,
       MULTIPLE_D_AND_F_IND,
        la_earned,
       la_needed,
       ma_earned,
       ma_needed,
       sc_earned,
       sc_needed,
       ss_earned,
       ss_needed,
       af_earned,
       af_needed,
       he_earned,
       he_needed,
       pe_earned,
       pe_needed,
       os_earned,
       os_needed,
        OSAS_ELA,
        OSAS_MATH
)
SELECT distinct
	student_name AS "C6442",
	student_id AS "C6443",
	local_school_year AS "C9055",
	curr_school AS "C6208",
	curr_grade AS "C6209",
	student_gender AS "C6290",
	student_race AS "C6291",
	STUDENT_SPECIAL_ED_CLASS  AS "C6444",
	student_home_language  AS "C6213",
	ELL2  AS "C6214",
	p504  AS "C6215",
	AVID AS "C6216",
	homeless AS "C6217",
	ihs  AS "C6218",
	migrant_ed  AS "C6219",
	title AS "C6220",
	curryr_att  AS "C6221",
	diploma_type  AS "C6210",
	curr_cum_gpa  AS "C6222",
	on_track  AS "C6223",
	CREDIT_AT_RISK AS "C6228",
	TOTAL_ACADEMIC_RISK  AS "C6229",
	ATTENDANCE_AT_RISK AS "C6231",
	 OAKS_MATH_ELA_PL_RISK AS "C6232",
	OSAS_ELA AS "C6285",
	OSAS_MATH AS "C6284",
	disc_at_risk AS "C6225",
	case when NUMBER_OF_DISC_INC is null then 0 else NUMBER_OF_DISC_INC end AS "C6224",
	TOTAL_OVERALL_RISK  AS "C6230",
	ELA_D_AND_F_CNT AS "C6233",
	MATH_D_AND_F_CNT  AS "C6234",
	SCI_D_AND_F_CNT  AS "C6235",
	 SS_D_AND_F_CNT AS "C6236",
	DF_COURSE_1  AS "C6237",
	DF_COURSE_2 AS "C6238",
	 DF_COURSE_3  AS "C6239",
	DF_COURSE_4 AS "C6240",
	DF_COURSE_5 AS "C6241",
	DF_COURSE_6 AS "C6242",
	MULTIPLE_D_AND_F_IND AS "C6243",
	tri1_course1 AS "C9274",
	tri1_mark1 AS "C9349",
	tri1_subject1 AS "C9296",
	tri1_staff1 AS "C9282",
	tri1_staff_id1 AS "C9325",
	tri1_course2 AS "C9275",
	tri1_mark2 AS "C9350",
	tri1_subject2 AS "C9302",
	tri1_staff2 AS "C9283",
	tri1_staff_id2 AS "C9326",
	tri1_course3 AS "C9276",
	tri1_mark3 AS "C9351",
	tri1_subject3 AS "C9303",
	tri1_staff3 AS "C9290",
	tri1_staff_id3 AS "C9327",
	tri1_course4 AS "C9277",
	tri1_mark4 AS "C9352",
	tri1_subject4 AS "C9304",
	tri1_staff4 AS "C9291",
	tri1_staff_id4 AS "C9328",
	tri1_course5 AS "C9278",
	tri1_mark5 AS "C9353",
	tri1_subject5 AS "C9305",
	tri1_staff5 AS "C9292",
	tri1_staff_id5 AS "C9329",
	tri1_course6 AS "C9279",
	tri1_mark6 AS "C9354",
	tri1_subject6 AS "C9306",
	tri1_staff6 AS "C9293",
	tri1_staff_id6 AS "C9330",
	tri1_course7 AS "C9280",
	tri1_mark7 AS "C9355",
	tri1_subject7 AS "C9307",
	tri1_staff7 AS "C9294",
	tri1_staff_id7 AS "C9331",
	tri1_course8 AS "C9281",
	tri1_mark8 AS "C9356",
	tri1_subject8 AS "C9308",
	tri1_staff8 AS "C9295",
	tri1_staff_id8 AS "C9332",
	tri2_course1 AS "C6244",
	tri2_subject1 AS "C9309",
	tri2_mark1 AS "C9357",
	tri2_staff1 AS "C6260",
	tri2_staff_id1 AS "C9333",
	tri2_course2 AS "C6245",
	tri2_mark2 AS "C9358",
	tri2_subject2 AS "C9310",
	tri2_staff2 AS "C6261",
	tri2_staff_id2 AS "C9334",
	tri2_course3 AS "C6254",
	tri2_mark3 AS "C9359",
	tri2_subject3 AS "C9311",
	tri2_staff3 AS "C6262",
	tri2_staff_id3 AS "C9335",
	tri2_course4 AS "C6255",
	tri2_mark4 AS "C9360",
	tri2_subject4 AS "C9312",
	tri2_staff4 AS "C6263",
	tri2_staff_id4 AS "C9336",
	tri2_course5 AS "C6256",
	tri2_mark5 AS "C9361",
	tri2_subject5 AS "C9313",
	tri2_staff5 AS "C6264",
	tri2_staff_id5 AS "C9337",
	tri2_course6 AS "C6257",
	tri2_mark6 AS "C9362",
	tri2_subject6 AS "C9314",
	tri2_staff6 AS "C6265",
	tri2_staff_id6 AS "C9338",
	tri2_course7 AS "C6258",
	tri2_mark7 AS "C9363",
	tri2_subject7 AS "C9315",
	tri2_staff7 AS "C6266",
	tri2_staff_id7 AS "C9339",
	tri2_course8 AS "C6259",
	tri2_mark8 AS "C9364",
	tri2_subject8 AS "C9316",
	tri2_staff8 AS "C6267",
	tri2_staff_id8 AS "C9340",
	tri3_course1  AS "C6268",
	tri3_mark1 AS "C9365",
	tri3_subject1 AS "C9317",
	tri3_staff1 AS "C6276",
	tri3_staff_id1 AS "C9341",
	tri3_course2 AS "C6269",
	tri3_mark2 AS "C9372",
	tri3_subject2 AS "C9318",
	tri3_staff2 AS "C6277",
	tri3_staff_id2 AS "C9342",
	tri3_course3 AS "C6270",
	tri3_mark3 AS "C9373",
	tri3_subject3 AS "C9319",
	tri3_staff3 AS "C6278",
	tri3_staff_id3 AS "C9343",
	tri3_course4 AS "C6271",
	tri3_mark4 AS "C9374",
	tri3_subject4 AS "C9320",
	tri3_staff4 AS "C6279",
	tri3_staff_id4 AS "C9344",
	tri3_course5 AS "C6272",
	tri3_mark5 AS "C9375",
	tri3_subject5 AS "C9321",
	tri3_staff5 AS "C6280",
	tri3_staff_id5 AS "C9345",
	tri3_course6 AS "C6273",
	tri3_mark6 AS "C9376",
	tri3_subject6 AS "C9322",
	tri3_staff6 AS "C6281",
	tri3_staff_id6 AS "C9346",
	tri3_course7  AS "C6274",
	tri3_mark7 AS "C9377",
	tri3_subject7 AS "C9323",
	tri3_staff7 AS "C6282",
	tri3_staff_id7 AS "C9347",
	tri3_course8 AS "C6275",
	tri3_mark8 AS "C9378",
	tri3_subject8 AS "C9324",
	tri3_staff8 AS "C6283",
	tri3_staff_id8 AS "C9348",
	la_earned AS "C6306",
	la_needed AS "C6316",
	ma_earned AS "C6307",
	ma_needed AS "C6317",
	sc_earned AS "C6308",
	sc_needed AS "C6318",
	ss_earned AS "C6309",
	ss_needed AS "C6319",
	af_earned AS "C6310",
	af_needed AS "C6320",
	he_earned AS "C6311",
	he_needed AS "C6321",
	pe_earned AS "C6312",
	pe_needed AS "C6322",
	os_earned AS "C6313",
	os_needed AS "C6323",
	on_track_credits  AS "C6227",
	student_key AS "C6445"
FROM
	 query
ORDER BY
	student_name,
	student_id,
	local_school_year,
	curr_school,
	curr_grade,
	student_gender,
	student_race,
	STUDENT_SPECIAL_ED_CLASS,
	student_home_language,
	ELL2,
	p504,
	AVID,
	homeless,
	ihs,
	migrant_ed,
	title,
	curryr_att,
	diploma_type,
	curr_cum_gpa,
	on_track,
	CREDIT_AT_RISK,
	TOTAL_ACADEMIC_RISK,
	ATTENDANCE_AT_RISK,
	OAKS_MATH_ELA_PL_RISK,
	OSAS_ELA,
	OSAS_MATH,
	disc_at_risk,
	case when NUMBER_OF_DISC_INC is null then 0 else NUMBER_OF_DISC_INC end,
	TOTAL_OVERALL_RISK,
	ELA_D_AND_F_CNT,
	MATH_D_AND_F_CNT,
	SCI_D_AND_F_CNT,
	SS_D_AND_F_CNT,
	DF_COURSE_1,
	DF_COURSE_2,
	DF_COURSE_3,
	DF_COURSE_4,
	DF_COURSE_5,
	DF_COURSE_6,
	MULTIPLE_D_AND_F_IND,
	tri1_course1,
	tri1_mark1,
	tri1_subject1,
	tri1_staff1,
	tri1_staff_id1,
	tri1_course2,
	tri1_mark2,
	tri1_subject2,
	tri1_staff2,
	tri1_staff_id2,
	tri1_course3,
	tri1_mark3,
	tri1_subject3,
	tri1_staff3,
	tri1_staff_id3,
	tri1_course4,
	tri1_mark4,
	tri1_subject4,
	tri1_staff4,
	tri1_staff_id4,
	tri1_course5,
	tri1_mark5,
	tri1_subject5,
	tri1_staff5,
	tri1_staff_id5,
	tri1_course6,
	tri1_mark6,
	tri1_subject6,
	tri1_staff6,
	tri1_staff_id6,
	tri1_course7,
	tri1_mark7,
	tri1_subject7,
	tri1_staff7,
	tri1_staff_id7,
	tri1_course8,
	tri1_mark8,
	tri1_subject8,
	tri1_staff8,
	tri1_staff_id8,
	tri2_course1,
	tri2_subject1,
	tri2_mark1,
	tri2_staff1,
	tri2_staff_id1,
	tri2_course2,
	tri2_mark2,
	tri2_subject2,
	tri2_staff2,
	tri2_staff_id2,
	tri2_course3,
	tri2_mark3,
	tri2_subject3,
	tri2_staff3,
	tri2_staff_id3,
	tri2_course4,
	tri2_mark4,
	tri2_subject4,
	tri2_staff4,
	tri2_staff_id4,
	tri2_course5,
	tri2_mark5,
	tri2_subject5,
	tri2_staff5,
	tri2_staff_id5,
	tri2_course6,
	tri2_mark6,
	tri2_subject6,
	tri2_staff6,
	tri2_staff_id6,
	tri2_course7,
	tri2_mark7,
	tri2_subject7,
	tri2_staff7,
	tri2_staff_id7,
	tri2_course8,
	tri2_mark8,
	tri2_subject8,
	tri2_staff8,
	tri2_staff_id8,
	tri3_course1,
	tri3_mark1,
	tri3_subject1,
	tri3_staff1,
	tri3_staff_id1,
	tri3_course2,
	tri3_mark2,
	tri3_subject2,
	tri3_staff2,
	tri3_staff_id2,
	tri3_course3,
	tri3_mark3,
	tri3_subject3,
	tri3_staff3,
	tri3_staff_id3,
	tri3_course4,
	tri3_mark4,
	tri3_subject4,
	tri3_staff4,
	tri3_staff_id4,
	tri3_course5,
	tri3_mark5,
	tri3_subject5,
	tri3_staff5,
	tri3_staff_id5,
	tri3_course6,
	tri3_mark6,
	tri3_subject6,
	tri3_staff6,
	tri3_staff_id6,
	tri3_course7,
	tri3_mark7,
	tri3_subject7,
	tri3_staff7,
	tri3_staff_id7,
	tri3_course8,
	tri3_mark8,
	tri3_subject8,
	tri3_staff8,
	tri3_staff_id8,
	la_earned,
	la_needed,
	ma_earned,
	ma_needed,
	sc_earned,
	sc_needed,
	ss_earned,
	ss_needed,
	af_earned,
	af_needed,
	he_earned,
	he_needed,
	pe_earned,
	pe_needed,
	os_earned,
	os_needed,
	on_track_credits
	go