SELECT
	count (DISTINCT dtbl_students.student_id) as cnt,
	dtbl_students.student_race as race2,
	--DISTINCT dtbl_students.student_id,
	dtbl_students.student_gender_code,
	Dtbl_students.student_foodservice_indicator
FROM
	K12INTEL_DW.FTBL_ENROLLMENTS WITH (NOLOCK)
		INNER JOIN K12INTEL_DW.DTBL_STUDENTS WITH (NOLOCK) ON FTBL_ENROLLMENTS.STUDENT_KEY = DTBL_STUDENTS.STUDENT_KEY
		inner join dbo.ESD_UDStu WITH (NOLOCK) ON ESD_UDStu.sis_number = DTBL_STUDENTS.STUDENT_ID
		INNER JOIN K12INTEL_DW.DTBL_STUDENT_ANNUAL_ATTRIBS WITH (NOLOCK) ON FTBL_ENROLLMENTS.STUDENT_ANNUAL_ATTRIBS_KEY = DTBL_STUDENT_ANNUAL_ATTRIBS.STUDENT_ANNUAL_ATTRIBS_KEY
		INNER JOIN K12INTEL_DW.DTBL_SCHOOLS WITH (NOLOCK) ON FTBL_ENROLLMENTS.SCHOOL_KEY = DTBL_SCHOOLS.SCHOOL_KEY
		INNER JOIN K12INTEL_DW.DTBL_SCHOOL_DATES DTBL_SCHOOL_DATES_BEGIN_ENROLL WITH (NOLOCK) ON FTBL_ENROLLMENTS.SCHOOL_DATES_KEY_BEGIN_ENROLL = DTBL_SCHOOL_DATES_BEGIN_ENROLL.SCHOOL_DATES_KEY
		INNER JOIN K12INTEL_DW.DTBL_SCHOOL_DATES DTBL_SCHOOL_DATES_END_ENROLL WITH (NOLOCK) ON FTBL_ENROLLMENTS.SCHOOL_DATES_KEY_END_ENROLL = DTBL_SCHOOL_DATES_END_ENROLL.SCHOOL_DATES_KEY
		INNER JOIN K12INTEL_DW.DTBL_CALENDAR_DATES WITH (NOLOCK) ON FTBL_ENROLLMENTS.CAL_DATE_KEY_BEGIN_ENROLL = DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY
		INNER JOIN K12INTEL_USERDATA.XTBL_DOMAIN_DECODES DOMAIN_GRADE_CODE WITH (NOLOCK) ON DOMAIN_GRADE_CODE.DOMAIN_NAME = 'GRADE_CODE' AND DOMAIN_GRADE_CODE.DOMAIN_CODE = DTBL_STUDENT_ANNUAL_ATTRIBS.STUDENT_ANNUAL_GRADE_CODE
		
		
WHERE
	DTBL_SCHOOL_DATES_BEGIN_ENROLL.date_value <  '2020-03-15 00:00:00.000'
	AND DTBL_SCHOOL_DATES_END_ENROLL.date_value > '2019-09-13 00:00:00.000'
	--(getdate() between DTBL_SCHOOL_DATES_BEGIN_ENROLL.date_value 
	--	and DTBL_SCHOOL_DATES_END_ENROLL.date_value)
	 --AND (DTBL_STUDENTS.STUDENT_ACTIVITY_INDICATOR = 'ACTIVE')
	 --AND (domain_grade_code.domain_alternate_decode IN ('P1', 'PK', 'K', '01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', 'TR'))
	 AND dtbl_schools.school_key IN (1,2,4,7,10,12,15,16,17,19,21,22,23,25,26,27,31,33,35,36,37,40,41,42,44,45,49,68,69,133,1032,1043)
    --AND (domain_grade_code.domain_alternate_decode IN ('12'))
	--and school_name like ('%sped%')
 GROUP BY
	--dtbl_students.student_race,
	dtbl_students.student_gender_code
	,Dtbl_students.student_foodservice_indicator
 ORDER BY
	--dtbl_students.student_id
	--dtbl_students.student_race,
	dtbl_students.student_gender_code
	,Dtbl_students.student_foodservice_indicator
	
	